### ISSUE TITLE
Unable to Connect

### ISSUE THREAD

**Issue by tobsowo** [NerdbyteIO/FOSSBilling-CyberPanel#1]
I noticed there is no '/' between the hostname and API probably reason it did not connect.

`Could not resolve host: host.server.comapi for "https://host.server.comapi/verifyConn". (9999)`

**Comment by tobsowo** [comment]
I also noticed that this icon do not add the port to the URL instead just the host name.

![image](https://github.com/NerdbyteIO/FOSSBilling-CyberPanel/assets/5642737/f497654c-d939-4644-ba18-31d0ec7351a6)

**Comment by jsonkenyon** [comment]
Tobsowo, 

Thanks for opening this request.  Sorry to learn that this isn't logging in for you.  That is truly odd that it isn't adding the port or the forward slash for you.  

What PHP, OS are you running?  Can you also confirm that your connection settings look like the following?

![connection](https://github.com/NerdbyteIO/FOSSBilling-CyberPanel/assets/16505105/cd89266b-5acb-473e-a785-42d1d4de600a)

**Comment by tobsowo** [comment]
I'm using the Docker installation

**Comment by jsonkenyon** [comment]
Ah, okay so that makes a bit more sense then.  So in your case with you running it in docker I assume that there's no port?  If this is correct I have a feeling i know what the issue is.

**Comment by tobsowo** [comment]
From your screenshot I only added the port 8090 and it seems to be fine now, left it before because it was the default based on the form field note.

**Comment by jsonkenyon** [comment]
@tobsowo Indeed, you are correct.  It has to deal with this line of code, 

` $port          = !empty($this->_config['port']) ? ':'.$this->_config['port'].'/' : ''; `

So if the port is blank it doesn't add anything after it.  I've updated this and pushing the fix

`$port          = !empty($this->_config['port']) ? ':'.$this->_config['port'].'/' : ':8090/';`

Thanks for reporting this!

**Comment by tobsowo** [comment]
@jsonkenyon you are welcome.
